### ISSUE TITLE
请教如何使用1panel自动提交

### ISSUE THREAD

**Issue by dadaoerv** [tangchunwei/iptv-list#6]
感谢大佬分享，我看文件是利用1panel自动提交的。请教方法。
万分感谢

**Comment by piperTang** [comment]
我这个不好用，你用别人的吧，我自己都不用了，你可以用饭太硬的

**Comment by dadaoerv** [comment]
> 我这个不好用，你用别人的吧，我自己都不用了，你可以用饭太硬的

谢谢，我希望1panel自动提取Github仓库里的iptv文件，修改后再自动上传到我自己的仓库。
